[package]
name = "koto_serialize"
version = "0.10.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Serde serialization support for the Koto programming language"
homepage = "https://github.com/koto-lang/koto"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
koto_runtime = { path = "../runtime", version = "^0.10.0"}
serde = "1.0.0"
