[package]
name = "koto_serialize"
version = "0.1.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
koto_runtime = { path = "../runtime" }
serde = "1.0.0"
