[package]
name = "koto_cli"
version = "0.10.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A CLI and script runner for the Koto programming language"
homepage = "https://github.com/koto-lang/koto"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[[bin]]
name = "koto"
path = "src/main.rs"

[features]
default = []
jemalloc = ["jemallocator"]

[dependencies]
koto = { path = "../koto", version = "^0.10.0"}
koto_json = { path = "../../libs/json", version = "^0.10.0"}
koto_random = { path = "../../libs/random", version = "^0.10.0"}
koto_tempfile = { path = "../../libs/tempfile", version = "^0.10.0"}
koto_toml = { path = "../../libs/toml", version = "^0.10.0"}
koto_yaml = { path = "../../libs/yaml", version = "^0.10.0"}

crossterm = "0.22.1" # A crossplatform terminal library for manipulating terminals.
indexmap = "1.4.0"
unicode-width = "0.1.9" # Determine displayed width of `char` and `str` types

[dependencies.pulldown-cmark]
# Markdown parsing
version = "0.8.0"
default-features = false

[dependencies.pico-args]
version = "0.3.4"
default-features = false

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.3.2", optional = true }
