[package]
name = "koto_wasm"
version = "0.16.1"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
koto = { path = "../../" }

wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
