[package]
name = "koto_lexer"
version = "0.3.0"
authors = ["irh <ian.r.hobson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The lexer used by the Koto programming language"
homepage = "https://github.com/koto-lang/koto"
repository = "https://github.com/koto-lang/koto"
keywords = ["scripting", "language", "koto"]

[dependencies]
unicode-width = "0.1.7"
unicode-xid = "0.2.0"
